id: AB78490AF
title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
  for Mind Training'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:45:42.776595
  last_modified_at: 2022-03-01 04:45:42.776601
