id: AB78490AF
title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:45:42.770228
  last_modified_at: 2022-03-01 04:45:42.770237
