id: AB78490AF
title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:45:42.779558
  last_modified_at: 2022-03-01 04:45:42.779561
